name: update-diagrams

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.c4"

jobs:
  diagrams:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: clean images
        run: |
          git rm -r images/*

      - name: export
        uses: likec4/actions-export@v1
        with:
          out: images

      - name: add images
        run: |
          git add images/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update diagrams [skip ci]"